/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipo;

import javax.swing.JOptionPane;

/**
 *
 * @author Albert
 */
public class vistaPrototipo extends javax.swing.JFrame {

    String COMPARACION_MAYOR_IGUAL_QUE = ">= X=<";
    /**
     * Creates new form vistaPrototipo
     */
    public vistaPrototipo() {
        initComponents();
        CampoPromedioFinal.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LabelNombre = new javax.swing.JLabel();
        CampoPromedioInicial = new javax.swing.JTextField();
        LabelProfesion = new javax.swing.JLabel();
        SelectorProfesionInicial = new javax.swing.JComboBox<>();
        LabelPromedio = new javax.swing.JLabel();
        CampoPromedioFinal = new javax.swing.JTextField();
        CampoDeTextoNombre = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        SelectorComparacionPromedio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Angel Gonzalez", "Quimico", "79"},
                {"Anna Matos", "Arquitecto", "80"},
                {"Armando Santos", "Veterinario", "99"},
                {"Axel Juarez", "Ingeniero Civil", "67"},
                {"Bartolomeo Santos", "Arquitecto", "79"},
                {"Beatriz Cruz", "Medico Cirujano", "94"},
                {"Carmen Rodriguez", "Ingeniero Civil", "76"},
                {"Daniel Sansores", "Quimico", "85"},
                {"Damian Alcazar", "Quimico", "71"},
                {"Diego Cruz", "Veterinario", "90"},
                {"Maria Conrado", "Arquitecto", "83"},
                {"Natalia Lugo", "Veterinario", "89"},
                {"Omar Gonzales", "Medico Cirujano", "73"},
                {"Osvaldo Ortega", "Ingeniero Civil", "65"},
                {"Patricia Romo", "Ingeniero Civil", "68"},
                {"Pedro Guzman", "Veterinario", "77"},
                {"Uriel Matos", "Arquitecto", "82"},
                {"Vanessa Dorantes", "Quimico", "95"},
                {"Waldo Lopez", "Medico Cirujano", null}
            },
            new String [] {
                "Nombre", "Profesion", "Promedio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        LabelNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelNombre.setText("Nombre:");

        CampoPromedioInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoPromedioInicialActionPerformed(evt);
            }
        });

        LabelProfesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelProfesion.setText("Profesion:");

        SelectorProfesionInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Arquitecto", "Ingeniero Civil", "Medico Cirujano", "Quimico", "Veterinario" }));
        SelectorProfesionInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectorProfesionInicialActionPerformed(evt);
            }
        });

        LabelPromedio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelPromedio.setText("Promedio:");

        BotonBuscar.setText("Buscar");

        SelectorComparacionPromedio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", ">=X", "X=<", "=X", ">= X=<" }));
        SelectorComparacionPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectorComparacionPromedioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelProfesion)
                            .addComponent(LabelPromedio)
                            .addComponent(LabelNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SelectorProfesionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(212, 212, 212)
                                .addComponent(BotonBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CampoPromedioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SelectorComparacionPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(CampoPromedioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CampoDeTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(CampoDeTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelProfesion)
                    .addComponent(SelectorProfesionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoPromedioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPromedio)
                    .addComponent(CampoPromedioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectorComparacionPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoPromedioInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoPromedioInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoPromedioInicialActionPerformed

    private void SelectorProfesionInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectorProfesionInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectorProfesionInicialActionPerformed

    private void SelectorComparacionPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectorComparacionPromedioActionPerformed
        if(SelectorComparacionPromedio.getSelectedItem()==COMPARACION_MAYOR_IGUAL_QUE){
            CampoPromedioFinal.setEditable(true);
        }else{
            CampoPromedioFinal.setEditable(false);
        }
    }//GEN-LAST:event_SelectorComparacionPromedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrototipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrototipo().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JTextField CampoDeTextoNombre;
    private javax.swing.JTextField CampoPromedioFinal;
    private javax.swing.JTextField CampoPromedioInicial;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelProfesion;
    private javax.swing.JLabel LabelPromedio;
    private javax.swing.JComboBox<String> SelectorComparacionPromedio;
    private javax.swing.JComboBox<String> SelectorProfesionInicial;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
